/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationManagerRouteImport } from './routes/location-manager'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as LocationManagerIndexRouteImport } from './routes/location-manager.index'
import { Route as GuardianIndexRouteImport } from './routes/guardian.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffSquadRouteImport } from './routes/staff.squad'
import { Route as StaffSessionsRouteImport } from './routes/staff.sessions'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as LocationManagerWaitlistRouteImport } from './routes/location-manager.waitlist'
import { Route as LocationManagerSessionsRouteImport } from './routes/location-manager.sessions'
import { Route as LocationManagerParticipantsRouteImport } from './routes/location-manager.participants'
import { Route as LocationManagerDashboardRouteImport } from './routes/location-manager.dashboard'
import { Route as LocationManagerCommunicationsRouteImport } from './routes/location-manager.communications'
import { Route as GuardianPaymentsRouteImport } from './routes/guardian.payments'
import { Route as GuardianDocumentsRouteImport } from './routes/guardian.documents'
import { Route as GuardianDashboardRouteImport } from './routes/guardian.dashboard'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinanceRemindersRouteImport } from './routes/finance.reminders'
import { Route as FinancePlansRouteImport } from './routes/finance.plans'
import { Route as FinanceInvoicesRouteImport } from './routes/finance.invoices'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceCollectionRouteImport } from './routes/finance.collection'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as GuardianPaymentsPayAllRouteImport } from './routes/guardian.payments.pay-all'
import { Route as GuardianParticipantIdRouteImport } from './routes/guardian.participant.$id'
import { Route as GuardianPaymentsSuccessAllRouteImport } from './routes/guardian.payments.success.all'
import { Route as GuardianPaymentsSuccessInvoiceIdRouteImport } from './routes/guardian.payments.success.$invoiceId'
import { Route as GuardianPaymentsPayInvoiceIdRouteImport } from './routes/guardian.payments.pay.$invoiceId'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationManagerRoute = LocationManagerRouteImport.update({
  id: '/location-manager',
  path: '/location-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const LocationManagerIndexRoute = LocationManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationManagerRoute,
} as any)
const GuardianIndexRoute = GuardianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardianRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffSquadRoute = StaffSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSessionsRoute = StaffSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffRoute,
} as any)
const LocationManagerWaitlistRoute = LocationManagerWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => LocationManagerRoute,
} as any)
const LocationManagerSessionsRoute = LocationManagerSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LocationManagerRoute,
} as any)
const LocationManagerParticipantsRoute =
  LocationManagerParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => LocationManagerRoute,
  } as any)
const LocationManagerDashboardRoute =
  LocationManagerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocationManagerRoute,
  } as any)
const LocationManagerCommunicationsRoute =
  LocationManagerCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => LocationManagerRoute,
  } as any)
const GuardianPaymentsRoute = GuardianPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianDocumentsRoute = GuardianDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuardianRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceRemindersRoute = FinanceRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePlansRoute = FinancePlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCollectionRoute = FinanceCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => FinanceRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const GuardianPaymentsPayAllRoute = GuardianPaymentsPayAllRouteImport.update({
  id: '/pay-all',
  path: '/pay-all',
  getParentRoute: () => GuardianPaymentsRoute,
} as any)
const GuardianParticipantIdRoute = GuardianParticipantIdRouteImport.update({
  id: '/participant/$id',
  path: '/participant/$id',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianPaymentsSuccessAllRoute =
  GuardianPaymentsSuccessAllRouteImport.update({
    id: '/success/all',
    path: '/success/all',
    getParentRoute: () => GuardianPaymentsRoute,
  } as any)
const GuardianPaymentsSuccessInvoiceIdRoute =
  GuardianPaymentsSuccessInvoiceIdRouteImport.update({
    id: '/success/$invoiceId',
    path: '/success/$invoiceId',
    getParentRoute: () => GuardianPaymentsRoute,
  } as any)
const GuardianPaymentsPayInvoiceIdRoute =
  GuardianPaymentsPayInvoiceIdRouteImport.update({
    id: '/pay/$invoiceId',
    path: '/pay/$invoiceId',
    getParentRoute: () => GuardianPaymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/location-manager': typeof LocationManagerRouteWithChildren
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/finance/collection': typeof FinanceCollectionRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/plans': typeof FinancePlansRoute
  '/finance/reminders': typeof FinanceRemindersRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/documents': typeof GuardianDocumentsRoute
  '/guardian/payments': typeof GuardianPaymentsRouteWithChildren
  '/location-manager/communications': typeof LocationManagerCommunicationsRoute
  '/location-manager/dashboard': typeof LocationManagerDashboardRoute
  '/location-manager/participants': typeof LocationManagerParticipantsRoute
  '/location-manager/sessions': typeof LocationManagerSessionsRoute
  '/location-manager/waitlist': typeof LocationManagerWaitlistRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/sessions': typeof StaffSessionsRoute
  '/staff/squad': typeof StaffSquadRoute
  '/admin/': typeof AdminIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/location-manager/': typeof LocationManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/guardian/participant/$id': typeof GuardianParticipantIdRoute
  '/guardian/payments/pay-all': typeof GuardianPaymentsPayAllRoute
  '/guardian/payments/pay/$invoiceId': typeof GuardianPaymentsPayInvoiceIdRoute
  '/guardian/payments/success/$invoiceId': typeof GuardianPaymentsSuccessInvoiceIdRoute
  '/guardian/payments/success/all': typeof GuardianPaymentsSuccessAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/finance/collection': typeof FinanceCollectionRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/plans': typeof FinancePlansRoute
  '/finance/reminders': typeof FinanceRemindersRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/documents': typeof GuardianDocumentsRoute
  '/guardian/payments': typeof GuardianPaymentsRouteWithChildren
  '/location-manager/communications': typeof LocationManagerCommunicationsRoute
  '/location-manager/dashboard': typeof LocationManagerDashboardRoute
  '/location-manager/participants': typeof LocationManagerParticipantsRoute
  '/location-manager/sessions': typeof LocationManagerSessionsRoute
  '/location-manager/waitlist': typeof LocationManagerWaitlistRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/sessions': typeof StaffSessionsRoute
  '/staff/squad': typeof StaffSquadRoute
  '/admin': typeof AdminIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/guardian': typeof GuardianIndexRoute
  '/location-manager': typeof LocationManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/guardian/participant/$id': typeof GuardianParticipantIdRoute
  '/guardian/payments/pay-all': typeof GuardianPaymentsPayAllRoute
  '/guardian/payments/pay/$invoiceId': typeof GuardianPaymentsPayInvoiceIdRoute
  '/guardian/payments/success/$invoiceId': typeof GuardianPaymentsSuccessInvoiceIdRoute
  '/guardian/payments/success/all': typeof GuardianPaymentsSuccessAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/location-manager': typeof LocationManagerRouteWithChildren
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/finance/collection': typeof FinanceCollectionRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/plans': typeof FinancePlansRoute
  '/finance/reminders': typeof FinanceRemindersRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/documents': typeof GuardianDocumentsRoute
  '/guardian/payments': typeof GuardianPaymentsRouteWithChildren
  '/location-manager/communications': typeof LocationManagerCommunicationsRoute
  '/location-manager/dashboard': typeof LocationManagerDashboardRoute
  '/location-manager/participants': typeof LocationManagerParticipantsRoute
  '/location-manager/sessions': typeof LocationManagerSessionsRoute
  '/location-manager/waitlist': typeof LocationManagerWaitlistRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/sessions': typeof StaffSessionsRoute
  '/staff/squad': typeof StaffSquadRoute
  '/admin/': typeof AdminIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/location-manager/': typeof LocationManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/guardian/participant/$id': typeof GuardianParticipantIdRoute
  '/guardian/payments/pay-all': typeof GuardianPaymentsPayAllRoute
  '/guardian/payments/pay/$invoiceId': typeof GuardianPaymentsPayInvoiceIdRoute
  '/guardian/payments/success/$invoiceId': typeof GuardianPaymentsSuccessInvoiceIdRoute
  '/guardian/payments/success/all': typeof GuardianPaymentsSuccessAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/finance'
    | '/guardian'
    | '/location-manager'
    | '/login'
    | '/staff'
    | '/admin/access'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/locations'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/finance/collection'
    | '/finance/dashboard'
    | '/finance/invoices'
    | '/finance/plans'
    | '/finance/reminders'
    | '/finance/reports'
    | '/guardian/dashboard'
    | '/guardian/documents'
    | '/guardian/payments'
    | '/location-manager/communications'
    | '/location-manager/dashboard'
    | '/location-manager/participants'
    | '/location-manager/sessions'
    | '/location-manager/waitlist'
    | '/staff/attendance'
    | '/staff/dashboard'
    | '/staff/sessions'
    | '/staff/squad'
    | '/admin/'
    | '/finance/'
    | '/guardian/'
    | '/location-manager/'
    | '/staff/'
    | '/guardian/participant/$id'
    | '/guardian/payments/pay-all'
    | '/guardian/payments/pay/$invoiceId'
    | '/guardian/payments/success/$invoiceId'
    | '/guardian/payments/success/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/access'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/locations'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/finance/collection'
    | '/finance/dashboard'
    | '/finance/invoices'
    | '/finance/plans'
    | '/finance/reminders'
    | '/finance/reports'
    | '/guardian/dashboard'
    | '/guardian/documents'
    | '/guardian/payments'
    | '/location-manager/communications'
    | '/location-manager/dashboard'
    | '/location-manager/participants'
    | '/location-manager/sessions'
    | '/location-manager/waitlist'
    | '/staff/attendance'
    | '/staff/dashboard'
    | '/staff/sessions'
    | '/staff/squad'
    | '/admin'
    | '/finance'
    | '/guardian'
    | '/location-manager'
    | '/staff'
    | '/guardian/participant/$id'
    | '/guardian/payments/pay-all'
    | '/guardian/payments/pay/$invoiceId'
    | '/guardian/payments/success/$invoiceId'
    | '/guardian/payments/success/all'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/finance'
    | '/guardian'
    | '/location-manager'
    | '/login'
    | '/staff'
    | '/admin/access'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/locations'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/finance/collection'
    | '/finance/dashboard'
    | '/finance/invoices'
    | '/finance/plans'
    | '/finance/reminders'
    | '/finance/reports'
    | '/guardian/dashboard'
    | '/guardian/documents'
    | '/guardian/payments'
    | '/location-manager/communications'
    | '/location-manager/dashboard'
    | '/location-manager/participants'
    | '/location-manager/sessions'
    | '/location-manager/waitlist'
    | '/staff/attendance'
    | '/staff/dashboard'
    | '/staff/sessions'
    | '/staff/squad'
    | '/admin/'
    | '/finance/'
    | '/guardian/'
    | '/location-manager/'
    | '/staff/'
    | '/guardian/participant/$id'
    | '/guardian/payments/pay-all'
    | '/guardian/payments/pay/$invoiceId'
    | '/guardian/payments/success/$invoiceId'
    | '/guardian/payments/success/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  GuardianRoute: typeof GuardianRouteWithChildren
  LocationManagerRoute: typeof LocationManagerRouteWithChildren
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-manager': {
      id: '/location-manager'
      path: '/location-manager'
      fullPath: '/location-manager'
      preLoaderRoute: typeof LocationManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/location-manager/': {
      id: '/location-manager/'
      path: '/'
      fullPath: '/location-manager/'
      preLoaderRoute: typeof LocationManagerIndexRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/guardian/': {
      id: '/guardian/'
      path: '/'
      fullPath: '/guardian/'
      preLoaderRoute: typeof GuardianIndexRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/squad': {
      id: '/staff/squad'
      path: '/squad'
      fullPath: '/staff/squad'
      preLoaderRoute: typeof StaffSquadRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/sessions': {
      id: '/staff/sessions'
      path: '/sessions'
      fullPath: '/staff/sessions'
      preLoaderRoute: typeof StaffSessionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/location-manager/waitlist': {
      id: '/location-manager/waitlist'
      path: '/waitlist'
      fullPath: '/location-manager/waitlist'
      preLoaderRoute: typeof LocationManagerWaitlistRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/location-manager/sessions': {
      id: '/location-manager/sessions'
      path: '/sessions'
      fullPath: '/location-manager/sessions'
      preLoaderRoute: typeof LocationManagerSessionsRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/location-manager/participants': {
      id: '/location-manager/participants'
      path: '/participants'
      fullPath: '/location-manager/participants'
      preLoaderRoute: typeof LocationManagerParticipantsRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/location-manager/dashboard': {
      id: '/location-manager/dashboard'
      path: '/dashboard'
      fullPath: '/location-manager/dashboard'
      preLoaderRoute: typeof LocationManagerDashboardRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/location-manager/communications': {
      id: '/location-manager/communications'
      path: '/communications'
      fullPath: '/location-manager/communications'
      preLoaderRoute: typeof LocationManagerCommunicationsRouteImport
      parentRoute: typeof LocationManagerRoute
    }
    '/guardian/payments': {
      id: '/guardian/payments'
      path: '/payments'
      fullPath: '/guardian/payments'
      preLoaderRoute: typeof GuardianPaymentsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/documents': {
      id: '/guardian/documents'
      path: '/documents'
      fullPath: '/guardian/documents'
      preLoaderRoute: typeof GuardianDocumentsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reminders': {
      id: '/finance/reminders'
      path: '/reminders'
      fullPath: '/finance/reminders'
      preLoaderRoute: typeof FinanceRemindersRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/plans': {
      id: '/finance/plans'
      path: '/plans'
      fullPath: '/finance/plans'
      preLoaderRoute: typeof FinancePlansRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/collection': {
      id: '/finance/collection'
      path: '/collection'
      fullPath: '/finance/collection'
      preLoaderRoute: typeof FinanceCollectionRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guardian/payments/pay-all': {
      id: '/guardian/payments/pay-all'
      path: '/pay-all'
      fullPath: '/guardian/payments/pay-all'
      preLoaderRoute: typeof GuardianPaymentsPayAllRouteImport
      parentRoute: typeof GuardianPaymentsRoute
    }
    '/guardian/participant/$id': {
      id: '/guardian/participant/$id'
      path: '/participant/$id'
      fullPath: '/guardian/participant/$id'
      preLoaderRoute: typeof GuardianParticipantIdRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/payments/success/all': {
      id: '/guardian/payments/success/all'
      path: '/success/all'
      fullPath: '/guardian/payments/success/all'
      preLoaderRoute: typeof GuardianPaymentsSuccessAllRouteImport
      parentRoute: typeof GuardianPaymentsRoute
    }
    '/guardian/payments/success/$invoiceId': {
      id: '/guardian/payments/success/$invoiceId'
      path: '/success/$invoiceId'
      fullPath: '/guardian/payments/success/$invoiceId'
      preLoaderRoute: typeof GuardianPaymentsSuccessInvoiceIdRouteImport
      parentRoute: typeof GuardianPaymentsRoute
    }
    '/guardian/payments/pay/$invoiceId': {
      id: '/guardian/payments/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/guardian/payments/pay/$invoiceId'
      preLoaderRoute: typeof GuardianPaymentsPayInvoiceIdRouteImport
      parentRoute: typeof GuardianPaymentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FinanceRouteChildren {
  FinanceCollectionRoute: typeof FinanceCollectionRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinancePlansRoute: typeof FinancePlansRoute
  FinanceRemindersRoute: typeof FinanceRemindersRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCollectionRoute: FinanceCollectionRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinancePlansRoute: FinancePlansRoute,
  FinanceRemindersRoute: FinanceRemindersRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface GuardianPaymentsRouteChildren {
  GuardianPaymentsPayAllRoute: typeof GuardianPaymentsPayAllRoute
  GuardianPaymentsPayInvoiceIdRoute: typeof GuardianPaymentsPayInvoiceIdRoute
  GuardianPaymentsSuccessInvoiceIdRoute: typeof GuardianPaymentsSuccessInvoiceIdRoute
  GuardianPaymentsSuccessAllRoute: typeof GuardianPaymentsSuccessAllRoute
}

const GuardianPaymentsRouteChildren: GuardianPaymentsRouteChildren = {
  GuardianPaymentsPayAllRoute: GuardianPaymentsPayAllRoute,
  GuardianPaymentsPayInvoiceIdRoute: GuardianPaymentsPayInvoiceIdRoute,
  GuardianPaymentsSuccessInvoiceIdRoute: GuardianPaymentsSuccessInvoiceIdRoute,
  GuardianPaymentsSuccessAllRoute: GuardianPaymentsSuccessAllRoute,
}

const GuardianPaymentsRouteWithChildren =
  GuardianPaymentsRoute._addFileChildren(GuardianPaymentsRouteChildren)

interface GuardianRouteChildren {
  GuardianDashboardRoute: typeof GuardianDashboardRoute
  GuardianDocumentsRoute: typeof GuardianDocumentsRoute
  GuardianPaymentsRoute: typeof GuardianPaymentsRouteWithChildren
  GuardianIndexRoute: typeof GuardianIndexRoute
  GuardianParticipantIdRoute: typeof GuardianParticipantIdRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianDashboardRoute: GuardianDashboardRoute,
  GuardianDocumentsRoute: GuardianDocumentsRoute,
  GuardianPaymentsRoute: GuardianPaymentsRouteWithChildren,
  GuardianIndexRoute: GuardianIndexRoute,
  GuardianParticipantIdRoute: GuardianParticipantIdRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

interface LocationManagerRouteChildren {
  LocationManagerCommunicationsRoute: typeof LocationManagerCommunicationsRoute
  LocationManagerDashboardRoute: typeof LocationManagerDashboardRoute
  LocationManagerParticipantsRoute: typeof LocationManagerParticipantsRoute
  LocationManagerSessionsRoute: typeof LocationManagerSessionsRoute
  LocationManagerWaitlistRoute: typeof LocationManagerWaitlistRoute
  LocationManagerIndexRoute: typeof LocationManagerIndexRoute
}

const LocationManagerRouteChildren: LocationManagerRouteChildren = {
  LocationManagerCommunicationsRoute: LocationManagerCommunicationsRoute,
  LocationManagerDashboardRoute: LocationManagerDashboardRoute,
  LocationManagerParticipantsRoute: LocationManagerParticipantsRoute,
  LocationManagerSessionsRoute: LocationManagerSessionsRoute,
  LocationManagerWaitlistRoute: LocationManagerWaitlistRoute,
  LocationManagerIndexRoute: LocationManagerIndexRoute,
}

const LocationManagerRouteWithChildren = LocationManagerRoute._addFileChildren(
  LocationManagerRouteChildren,
)

interface StaffRouteChildren {
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffSessionsRoute: typeof StaffSessionsRoute
  StaffSquadRoute: typeof StaffSquadRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffSessionsRoute: StaffSessionsRoute,
  StaffSquadRoute: StaffSquadRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  GuardianRoute: GuardianRouteWithChildren,
  LocationManagerRoute: LocationManagerRouteWithChildren,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
